import type { Metadata } from "next";
import { Raleway, Bodoni_Moda } from "next/font/google";
import "./globals.css";
import AuthProvider from "./context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import { LoadingProvider } from "@/app/context/LoadingContext";
import AppWrapper from "@/components/AppWrapper";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const bodoniModa = Bodoni_Moda({
  variable: "--font-bodoni",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "krishnakumbhaj",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${raleway.variable} ${bodoniModa.variable}`}>
      <body className={`${raleway.className} antialiased`}>
        <AuthProvider>
          <LoadingProvider>
            <AppWrapper>
              {children}
            </AppWrapper>
          </LoadingProvider>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
